### ISSUE TITLE
Showcase has leaks - Items Lost

### ISSUE THREAD

**Issue by WizWazWizard** [NaspoDev/Showcase#1]
I put items into /showcase, restart my server, and they're all gone. Comes up with "Doesn't have a showcase"

**Comment by NaspoDev** [comment]
Hello, I'm so sorry to hear that you're having problems with the plugin! 

Can you please give me the following information:
- The plugin version you're using.
- The jar your server is running on and the version of MC.
- Are there any logs you see in the console on startup or shutdown? Maybe something indicating data save or restore problems. If there are, please also post them.

Thank you very much!

**Comment by NaspoDev** [comment]
Spoke on discord.

**Conclusion:**
Cannot reproduce.
